disabled_rules:
  - file_header
  - force_try
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - type_body_length
  - type_name
  - xctfail_message
  - weak_delegate # This would be interesting to re-enable,
                  # because it could easily help us avoid ugly retain loops,
                  # but we have some existing violations we should look at first

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - file_header
  - first_where
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - void_return
  # Find all the available rules by running:
  # swiftlint rules

excluded:
  - Pods
  - Generated/Generated.swift

force_cast: warning
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
